### ISSUE TITLE
Rates missing for different range of transactions

### ISSUE THREAD

**Issue by dhruvam-gupta** [sahilgupta/sbi-fx-ratekeeper#6]
exchange rates for buy/sell prices differ for transaction limit below and above Rs. 10 Lakhs
I see the rates are mentioned for transactions above 10 Lakhs. Can it be corrected?

**Comment by sahilgupta** [comment]
The SBI explicitly mentions that the reference rates are the ones they use for 10-20 lakh transaction range.

The reference rates don’t change based on your  transaction value, which could ₹100 or ₹1 Cr.

This is be design.
