### ISSUE TITLE
PDF has image instead of text

### ISSUE THREAD

**Issue by gotspatel** [sahilgupta/sbi-fx-ratekeeper#9]
hi 

the pdf has images instead of the text hence no data is able to be extracted

can you please check and update.

Regards

**Comment by sahilgupta** [comment]
Thanks for raising this. Seems like this was a temporary glitch on the SBI side. The recent PDFs have text.

Nevertheless, I have added Anthropic API as a fallback to process the PDF as an image in case this happens again.
